// export const COLOR_MILK = "#fcfbf9";
export const COLOR_MILK = "#edfaff";
export const MOBILE_TELEPHONE: string = "7-925-731-81-52";
export const IP = { name: "ИП Блохин Д.В.", OGRNIP: "123456789123456", INN: "123456789122" };
export const EMAIL: string = "info@voda-bsv.ru";
export const NICKTELEGRAM = "blohinsergei";
export const DEV = false;
// export const DEV = true;
export const INN = "";
